version: '3.3'

name: 3lm

services:
  embed:
    container_name: embed-cont
    image: embed:v1
    restart: always
    # platform: linux/amd64
    env_file:
      - .env 
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: 1  # enable buildkit
    volumes:
      - "./app/model-store/:/app/model-store"
    ports:
      - "3004:3004"
    networks:
      - llm-net

networks:
  llm-net:
    name: llm-net
    external: true