version: '3.3'


services:
  embed:
    container_name: embed
    image: embed:v1
    restart: always
    platform: linux/amd64
    env_file:
      - ./.embed-env 
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: 1  
    volumes:
      - "../model-store/:/app/model-store"
    ports:
      - "3004:3004"
    networks:
      - llm-net

  nginx:
    image: nginx:latest 
    build: 
        context: .
        dockerfile: ./Dockerfile-nginx      
    ports:
      - "3002:3002"
    depends_on:
      - embed  
    networks:
      - llm-net   

networks:
  llm-net:
    name: llm-net
    external: true