FROM nginx:latest 
# Remove default Nginx config
RUN rm /etc/nginx/nginx.conf
# Copy the modified Nginx conf
COPY nginx/nginx.conf /etc/nginx
COPY nginx/.htpasswd /etc/nginx

# Copy proxy config
COPY nginx/local-rag.conf /etc/nginx/sites-enabled/