version: '3.3'


services:
  embed:
    container_name: embed-cont
    image: embed:v1
    restart: always
    platform: linux/amd64
    env_file:
      - .env 
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: 1  
    volumes:
      - "../model-store/:/app/model-store"
    ports:
    # visible only inside docker network
      - "3004:3004"
    networks:
      - llm-net

  nginx:
    image: nginx:latest 
    build: 
        context: .
        dockerfile: ./Dockerfile_nginx      
    ports:
      - "3002:3002"
    # volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/local-rag.conf:/etc/nginx/sites-enabled/local-rag.conf
      # - ./nginx/nginx/.htpasswd:/etc/nginx/.htpasswd
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - embed  
    networks:
      - llm-net   

networks:
  llm-net:
    name: llm-net
    external: true