version: '3.3'


services:
  embed:
    container_name: embed
    image: embed:v1
    restart: always
    platform: linux/amd64
    env_file:
      - ../client-files/.env 
    environment:
      HOST: ${HOST}
      EM_PORT: ${EM_PORT}
      DEVICE: ${DEVICE}
      N_CTX: ${N_CTX}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1  
    volumes:
      - "../model-store/:/app/model-store"
    ports:
      - ${EM_PORT}:${EM_PORT}
    networks:
      - llm-net

  nginx:
    container_name: nginx
    restart: always    
    image: nginx:latest 
    # environment variables are not used currently
    environment:
      - HOST_SERVER_URI=${HOST_SERVER_URI} 
      - MAIN_MODEL_SERVER_URI=${MAIN_MODEL_SERVER_URI}
    build: 
        context: .
        dockerfile: Dockerfile-nginx      
    ports:
      - "3002:3002"
    depends_on:
      - embed  
    networks:
      - llm-net
    volumes:
      - ../client-files/nginx:/etc/nginx/sites-enabled/

  postgres:
    container_name: postgres
    build: ./postgres
    image: pgembeding
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - llm-net   
    depends_on:
      - nginx 
      - embed

volumes:
  pgdata:      

networks:
  llm-net:
    name: llm-net
    external: true