version: '3.3'

services:
  llm-server:
    container_name: llm-server
    restart: always
    image: llm-server:v2
    platform: linux/amd64
    environment:
      HOST: ${HOST}
      MM_PORT: ${MM_PORT}
      DEVICE: ${DEVICE}
      N_CTX: ${N_CTX}
      COMPLETION_MODEL_NAME: ${COMPLETION_MODEL_NAME}
      # N_GPU_LAYERS: ${N_GPU_LAYERS}
      CHAT_FORMAT: ${CHAT_FORMAT}    
      TRANSFORMERS_OFFLINE: 1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - "../../../model-store:/app/model-store" 
    ports:
      - ${MM_PORT}:${MM_PORT}
    ulimits:
      memlock:
        soft: -1
        hard: -1      

    networks:
      - llm-net
networks:
  llm-net:
    name: llm-net
    external: true