version: '3.8'

services:
  vllm:
    container_name: vllm
    # image: ghcr.io/mistralai/mistral-src/vllm:latest
    # image: docker.io/vllm/vllm-openai:latest
    image: vllm/vllm-openai:latest
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${MM_PORT}
      DEVICE: ${DEVICE}
      COMPLETION_MODEL_NAME: ${COMPLETION_MODEL_NAME}
      CUDA_HOME: "/usr/local/cuda"
      NVIDIA_VISIBLE_DEVICES: all
      TP_SIZE: ${TP_SIZE}
      CHAT_FORMAT: ${CHAT_TEMPLATE}
    command:
      - "--host=${HOST}"
      - "--port=${MM_PORT}"
      - "--model=/model-store/${COMPLETION_MODEL_NAME}"
      - "--chat-template=${CHAT_FORMAT}"
      - "--tensor-parallel-size=${TP_SIZE}"
    volumes:
      - "../../model-store/:/model-store"
    ports:
      - ${MM_PORT}:${MM_PORT}
    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]      
    networks:
      - llm-net
networks:
  llm-net:
    name: llm-net
    external: true              
