version: '3.8'

services:
  vllm:
    container_name: vllm
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    restart: always
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "3003"
      - "--model=/${COMPLETION_MODEL_NAME}"
      # - "--model=/model-store/mistralai/Mistral-7B-Instruct-v0.1"
    volumes:
      - "../../model-store/:/model-store"
    ports:
      - "3003:3003"
    environment:
      HOST: 0.0.0.0
      PORT: 3003
      DEVICE: ${DEVICE}
      COMPLETION_MODEL_NAME: ${COMPLETION_MODEL_NAME}
      CUDA_HOME: "/usr/local/cuda"
      NVIDIA_VISIBLE_DEVICES: all      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]      
    networks:
      - llm-net
networks:
  llm-net:
    name: llm-net
    external: true              
