version: '3.8'

services:
  model_downloader:
    build: .
    volumes:
      - ../../../model-store:/model-store    
    environment:
      - MODEL_NAME=openchat/openchat_3.5
    mem_limit: 24G

# docker-compose up --build