version: '3.9'

services:
  anyth:
    container_name: anyth
    restart: always
    image: anyth-cpu:v1
    platform: linux/amd64
    env_file:
      - ../../client-files/.env 
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID}
        ARG_GID: ${GID}
        DOCKER_BUILDKIT: 1  
    volumes:
    # ensure all host dirs have the same permissions as the container user
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID}:${GID}"
    ports:
      - "3001:3001"
    networks:
      - llm-net
networks:
  llm-net:
    name: llm-net
    external: true