version: '3.9'

services:
  anyth:
    container_name: anyth
    restart: always
    image: anyth:last_com
    platform: linux/amd64
    env_file:
      - ../../client-files/.env
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${ARG_UID}
        ARG_GID: ${ARG_GID}
        DOCKER_BUILDKIT: 1  
    environment:
      - DOCKER_BUILDKIT=1
    volumes:
    # ensure all host dirs have the same permissions as the container user
      - "../server/storage/:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
      - "../server/storage/coder:/app/server/storage/coder"
    user: "${ARG_UID}:${ARG_GID}"
    ports:
      - 3001:3001
      - 3006:3006
      - 3005:3005
    networks:
      - llm-net
networks:
  llm-net:
    name: llm-net
    external: true