version: '3.1'

services:
  postgres:
    container_name: postgres
    # build: .  
    image: pgembeding
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - llm-net   

networks:
  llm-net:
    name: llm-net
    external: true

volumes:
  pgdata:

# docker-compose -p localrag up -d --build

# this instructions are implemented in composite docker-compose.yml at one level up folder
# to reinitialize database run:  embed-server/postgres/reinit-db.sh